### ISSUE TITLE
CSS Errors while using it with Nextjs.

### ISSUE THREAD

**Issue by jackkweyunga** [flexcodelabs/sarufi-chatbox#32]
I used the package to display a chatbox in my nextjs application, but unfortunately I did not succeed coz I kept getting errors no matter where I placed the code as shown in the example.

![image](https://user-images.githubusercontent.com/75433841/230208916-4d649622-99a9-4456-b3a9-9d9f31c1be6b.png)

![image](https://user-images.githubusercontent.com/75433841/230209284-6b745155-f40e-47e1-8d5f-fc3a2731e09e.png)

**Comment by jackkweyunga** [comment]
Here is a text version of the error

./node_modules/react-sarufi-chatbox/lib/esm/chat/chat.module.css
CSS Modules cannot be imported from within node_modules.
Read more: [https://nextjs.org/docs/messages/css-modules-npm](https://nextjs.org/docs/messages/css-modules-npm)
Location: node_modules\react-sarufi-chatbox\lib\esm\chat\chat.js

**Comment by jackkweyunga** [comment]
In nextjs, a workaround could be to use next/script together with the same vanilla-js code.

```js
<Script
    id={'chatbox'}
    strategy="afterInteractive"
    dangerouslySetInnerHTML={{
        __html: `document.addEventListener('DOMContentLoaded', function() {
                // setting global variables
                window.botId = <bot_id>
                
                // create div with id = sarufi-chatbox
                const div = document.createElement("div")
                div.id = "sarufi-chatbox"
                document.body.appendChild(div)
            
                // create and attach script tag
                const script = document.createElement("script")
                script.crossOrigin = true
                script.type = "module"
                script.src = "https://cdn.jsdelivr.net/gh/flexcodelabs/sarufi-chatbox/example/vanilla-js/script.js"
                document.head.appendChild(script)
            
                // create and attach css
                const style = document.createElement("link")
                style.crossOrigin = true
                style.rel = "stylesheet"
                style.href = "https://cdn.jsdelivr.net/gh/flexcodelabs/sarufi-chatbox/example/vanilla-js/style.css"
                document.head.appendChild(style)
              });`,
    }}
/>
```

**Comment by bmsteven** [comment]
the issue should be fixed now, but the component is heavily dependent to CSR, so to render it without errors, you will need to use client side rendering

**Comment by jackkweyunga** [comment]
Ok, I updated to the current version.
Still it does not work no matter where I place the element in my next js app, it throws same error. Am not sure what's wrong.
The link below is part of the logs and it has some suggested fixes to the issue
[https://nextjs.org/docs/messages/css-npm](https://nextjs.org/docs/messages/css-npm)

**Comment by jackkweyunga** [comment]
Nice One ... I'll try it.

If that's the way next js developers need to do to make the package work ... then I think such special use cases should be included in the docs.

**Comment by bmsteven** [comment]
Yes there are lots of packages that uses css without modules and by default that won't work on nextjs.
In next v13, you can migrate your next to use app directory instead of pages which will allow css imports in node_modules. https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app I think this version isn't stable yet. You can check it out
